version: "3.7"
services:
  plantor:
    build: .
    environment:
      - MQTT_BROKER_HOST=mosquitto
      - MQTT_BROKER_PORT=1883
      - INFLUX_HOST=influxdb-grafana
      - INFLUX_PORT=8086
    networks:
      - local
  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - 1883:1883
    networks:
      - local
  influxdb-grafana:
    image: philhawthorne/docker-influxdb-grafana:latest
    environment:
      - INFLUXDB_HTTP_ENABLED=true
      - INFLUXDB_HTTP_AUTH_ENABLED=false
    ports:
      - 3003:3003
      - 3004:8003
      - 8086:8086
    networks:
      - local
    volumes:
      # influx
      - /srv/plantor/influxdb/data:/var/lib/influxdb
      # grafana
      - /srv/plantor/grafana/data:/var/lib/grafana
      - ./docker/grafana/provisioning:/etc/grafana/provisioning
networks:
  local:
    driver: bridge