version: "3.7"
services:
  plantor:
    build: .
    environment:
      - MQTT_BROKER_HOST=mosquitto
      - MQTT_BROKER_PORT=1883
      - INFLUX_HOST=influxdb
      - INFLUX_PORT=8086
    networks:
      - local
    restart: on-failure:5
  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - 1883:1883
    networks:
      - local
  influxdb:
    image: influxdb:latest
    environment:
      - INFLUXDB_DB=plantor
      - INFLUXDB_HTTP_ENABLED=true
      - INFLUXDB_HTTP_AUTH_ENABLED=false
      - INFLUXDB_ADMIN_USER=root
      - INFLUXDB_ADMIN_PASSWORD=root
    ports:
      - 8086:8086
    networks:
      - local
    volumes:
      - /srv/plantor/influxdb/data:/var/lib/influxdb
  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_USER=root
      - GF_SECURITY_ADMIN_PASSWORD=root
    ports:
      - 3000:3000
    networks:
      - local
    volumes:
      - /srv/plantor/grafana/data:/var/lib/grafana:rw
      - ./docker/grafana/provisioning:/etc/grafana/provisioning
networks:
  local:
    driver: bridge